[workspace]
channels = ["conda-forge"]
name = "Coastal_Sediments_2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
numpy = ">=2.3.2,<3"
scipy = ">=1.16.0,<2"
pymupdf = ">=1.26.1,<2"
matplotlib = ">=3.10.5,<4"
pytest = ">=8.4.1,<9"
sphinx = ">=8.2.3,<9"
